// This file was generated by counterfeiter
package azurefakes

import (
	"sync"

	"github.com/Azure/azure-sdk-for-go/arm/compute"
	"github.com/Azure/go-autorest/autorest"
	"github.com/pivotal-cf/cliaas/iaas/azure"
)

type FakeComputeVirtualMachinesClient struct {
	ListAllNextResultsStub        func(lastResults compute.VirtualMachineListResult) (result compute.VirtualMachineListResult, err error)
	listAllNextResultsMutex       sync.RWMutex
	listAllNextResultsArgsForCall []struct {
		lastResults compute.VirtualMachineListResult
	}
	listAllNextResultsReturns struct {
		result1 compute.VirtualMachineListResult
		result2 error
	}
	listAllNextResultsReturnsOnCall map[int]struct {
		result1 compute.VirtualMachineListResult
		result2 error
	}
	CreateOrUpdateStub        func(resourceGroupName string, vmName string, parameters compute.VirtualMachine, cancel <-chan struct{}) (result autorest.Response, err error)
	createOrUpdateMutex       sync.RWMutex
	createOrUpdateArgsForCall []struct {
		resourceGroupName string
		vmName            string
		parameters        compute.VirtualMachine
		cancel            <-chan struct{}
	}
	createOrUpdateReturns struct {
		result1 autorest.Response
		result2 error
	}
	createOrUpdateReturnsOnCall map[int]struct {
		result1 autorest.Response
		result2 error
	}
	DeleteStub        func(resourceGroupName string, vmName string, cancel <-chan struct{}) (result autorest.Response, err error)
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		resourceGroupName string
		vmName            string
		cancel            <-chan struct{}
	}
	deleteReturns struct {
		result1 autorest.Response
		result2 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 autorest.Response
		result2 error
	}
	DeallocateStub        func(resourceGroupName string, vmName string, cancel <-chan struct{}) (result autorest.Response, err error)
	deallocateMutex       sync.RWMutex
	deallocateArgsForCall []struct {
		resourceGroupName string
		vmName            string
		cancel            <-chan struct{}
	}
	deallocateReturns struct {
		result1 autorest.Response
		result2 error
	}
	deallocateReturnsOnCall map[int]struct {
		result1 autorest.Response
		result2 error
	}
	ListStub        func(resourceGroupName string) (result compute.VirtualMachineListResult, err error)
	listMutex       sync.RWMutex
	listArgsForCall []struct {
		resourceGroupName string
	}
	listReturns struct {
		result1 compute.VirtualMachineListResult
		result2 error
	}
	listReturnsOnCall map[int]struct {
		result1 compute.VirtualMachineListResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeComputeVirtualMachinesClient) ListAllNextResults(lastResults compute.VirtualMachineListResult) (result compute.VirtualMachineListResult, err error) {
	fake.listAllNextResultsMutex.Lock()
	ret, specificReturn := fake.listAllNextResultsReturnsOnCall[len(fake.listAllNextResultsArgsForCall)]
	fake.listAllNextResultsArgsForCall = append(fake.listAllNextResultsArgsForCall, struct {
		lastResults compute.VirtualMachineListResult
	}{lastResults})
	fake.recordInvocation("ListAllNextResults", []interface{}{lastResults})
	fake.listAllNextResultsMutex.Unlock()
	if fake.ListAllNextResultsStub != nil {
		return fake.ListAllNextResultsStub(lastResults)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listAllNextResultsReturns.result1, fake.listAllNextResultsReturns.result2
}

func (fake *FakeComputeVirtualMachinesClient) ListAllNextResultsCallCount() int {
	fake.listAllNextResultsMutex.RLock()
	defer fake.listAllNextResultsMutex.RUnlock()
	return len(fake.listAllNextResultsArgsForCall)
}

func (fake *FakeComputeVirtualMachinesClient) ListAllNextResultsArgsForCall(i int) compute.VirtualMachineListResult {
	fake.listAllNextResultsMutex.RLock()
	defer fake.listAllNextResultsMutex.RUnlock()
	return fake.listAllNextResultsArgsForCall[i].lastResults
}

func (fake *FakeComputeVirtualMachinesClient) ListAllNextResultsReturns(result1 compute.VirtualMachineListResult, result2 error) {
	fake.ListAllNextResultsStub = nil
	fake.listAllNextResultsReturns = struct {
		result1 compute.VirtualMachineListResult
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeVirtualMachinesClient) ListAllNextResultsReturnsOnCall(i int, result1 compute.VirtualMachineListResult, result2 error) {
	fake.ListAllNextResultsStub = nil
	if fake.listAllNextResultsReturnsOnCall == nil {
		fake.listAllNextResultsReturnsOnCall = make(map[int]struct {
			result1 compute.VirtualMachineListResult
			result2 error
		})
	}
	fake.listAllNextResultsReturnsOnCall[i] = struct {
		result1 compute.VirtualMachineListResult
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeVirtualMachinesClient) CreateOrUpdate(resourceGroupName string, vmName string, parameters compute.VirtualMachine, cancel <-chan struct{}) (result autorest.Response, err error) {
	fake.createOrUpdateMutex.Lock()
	ret, specificReturn := fake.createOrUpdateReturnsOnCall[len(fake.createOrUpdateArgsForCall)]
	fake.createOrUpdateArgsForCall = append(fake.createOrUpdateArgsForCall, struct {
		resourceGroupName string
		vmName            string
		parameters        compute.VirtualMachine
		cancel            <-chan struct{}
	}{resourceGroupName, vmName, parameters, cancel})
	fake.recordInvocation("CreateOrUpdate", []interface{}{resourceGroupName, vmName, parameters, cancel})
	fake.createOrUpdateMutex.Unlock()
	if fake.CreateOrUpdateStub != nil {
		return fake.CreateOrUpdateStub(resourceGroupName, vmName, parameters, cancel)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createOrUpdateReturns.result1, fake.createOrUpdateReturns.result2
}

func (fake *FakeComputeVirtualMachinesClient) CreateOrUpdateCallCount() int {
	fake.createOrUpdateMutex.RLock()
	defer fake.createOrUpdateMutex.RUnlock()
	return len(fake.createOrUpdateArgsForCall)
}

func (fake *FakeComputeVirtualMachinesClient) CreateOrUpdateArgsForCall(i int) (string, string, compute.VirtualMachine, <-chan struct{}) {
	fake.createOrUpdateMutex.RLock()
	defer fake.createOrUpdateMutex.RUnlock()
	return fake.createOrUpdateArgsForCall[i].resourceGroupName, fake.createOrUpdateArgsForCall[i].vmName, fake.createOrUpdateArgsForCall[i].parameters, fake.createOrUpdateArgsForCall[i].cancel
}

func (fake *FakeComputeVirtualMachinesClient) CreateOrUpdateReturns(result1 autorest.Response, result2 error) {
	fake.CreateOrUpdateStub = nil
	fake.createOrUpdateReturns = struct {
		result1 autorest.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeVirtualMachinesClient) CreateOrUpdateReturnsOnCall(i int, result1 autorest.Response, result2 error) {
	fake.CreateOrUpdateStub = nil
	if fake.createOrUpdateReturnsOnCall == nil {
		fake.createOrUpdateReturnsOnCall = make(map[int]struct {
			result1 autorest.Response
			result2 error
		})
	}
	fake.createOrUpdateReturnsOnCall[i] = struct {
		result1 autorest.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeVirtualMachinesClient) Delete(resourceGroupName string, vmName string, cancel <-chan struct{}) (result autorest.Response, err error) {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		resourceGroupName string
		vmName            string
		cancel            <-chan struct{}
	}{resourceGroupName, vmName, cancel})
	fake.recordInvocation("Delete", []interface{}{resourceGroupName, vmName, cancel})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(resourceGroupName, vmName, cancel)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.deleteReturns.result1, fake.deleteReturns.result2
}

func (fake *FakeComputeVirtualMachinesClient) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeComputeVirtualMachinesClient) DeleteArgsForCall(i int) (string, string, <-chan struct{}) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].resourceGroupName, fake.deleteArgsForCall[i].vmName, fake.deleteArgsForCall[i].cancel
}

func (fake *FakeComputeVirtualMachinesClient) DeleteReturns(result1 autorest.Response, result2 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 autorest.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeVirtualMachinesClient) DeleteReturnsOnCall(i int, result1 autorest.Response, result2 error) {
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 autorest.Response
			result2 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 autorest.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeVirtualMachinesClient) Deallocate(resourceGroupName string, vmName string, cancel <-chan struct{}) (result autorest.Response, err error) {
	fake.deallocateMutex.Lock()
	ret, specificReturn := fake.deallocateReturnsOnCall[len(fake.deallocateArgsForCall)]
	fake.deallocateArgsForCall = append(fake.deallocateArgsForCall, struct {
		resourceGroupName string
		vmName            string
		cancel            <-chan struct{}
	}{resourceGroupName, vmName, cancel})
	fake.recordInvocation("Deallocate", []interface{}{resourceGroupName, vmName, cancel})
	fake.deallocateMutex.Unlock()
	if fake.DeallocateStub != nil {
		return fake.DeallocateStub(resourceGroupName, vmName, cancel)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.deallocateReturns.result1, fake.deallocateReturns.result2
}

func (fake *FakeComputeVirtualMachinesClient) DeallocateCallCount() int {
	fake.deallocateMutex.RLock()
	defer fake.deallocateMutex.RUnlock()
	return len(fake.deallocateArgsForCall)
}

func (fake *FakeComputeVirtualMachinesClient) DeallocateArgsForCall(i int) (string, string, <-chan struct{}) {
	fake.deallocateMutex.RLock()
	defer fake.deallocateMutex.RUnlock()
	return fake.deallocateArgsForCall[i].resourceGroupName, fake.deallocateArgsForCall[i].vmName, fake.deallocateArgsForCall[i].cancel
}

func (fake *FakeComputeVirtualMachinesClient) DeallocateReturns(result1 autorest.Response, result2 error) {
	fake.DeallocateStub = nil
	fake.deallocateReturns = struct {
		result1 autorest.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeVirtualMachinesClient) DeallocateReturnsOnCall(i int, result1 autorest.Response, result2 error) {
	fake.DeallocateStub = nil
	if fake.deallocateReturnsOnCall == nil {
		fake.deallocateReturnsOnCall = make(map[int]struct {
			result1 autorest.Response
			result2 error
		})
	}
	fake.deallocateReturnsOnCall[i] = struct {
		result1 autorest.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeVirtualMachinesClient) List(resourceGroupName string) (result compute.VirtualMachineListResult, err error) {
	fake.listMutex.Lock()
	ret, specificReturn := fake.listReturnsOnCall[len(fake.listArgsForCall)]
	fake.listArgsForCall = append(fake.listArgsForCall, struct {
		resourceGroupName string
	}{resourceGroupName})
	fake.recordInvocation("List", []interface{}{resourceGroupName})
	fake.listMutex.Unlock()
	if fake.ListStub != nil {
		return fake.ListStub(resourceGroupName)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listReturns.result1, fake.listReturns.result2
}

func (fake *FakeComputeVirtualMachinesClient) ListCallCount() int {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return len(fake.listArgsForCall)
}

func (fake *FakeComputeVirtualMachinesClient) ListArgsForCall(i int) string {
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return fake.listArgsForCall[i].resourceGroupName
}

func (fake *FakeComputeVirtualMachinesClient) ListReturns(result1 compute.VirtualMachineListResult, result2 error) {
	fake.ListStub = nil
	fake.listReturns = struct {
		result1 compute.VirtualMachineListResult
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeVirtualMachinesClient) ListReturnsOnCall(i int, result1 compute.VirtualMachineListResult, result2 error) {
	fake.ListStub = nil
	if fake.listReturnsOnCall == nil {
		fake.listReturnsOnCall = make(map[int]struct {
			result1 compute.VirtualMachineListResult
			result2 error
		})
	}
	fake.listReturnsOnCall[i] = struct {
		result1 compute.VirtualMachineListResult
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeVirtualMachinesClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listAllNextResultsMutex.RLock()
	defer fake.listAllNextResultsMutex.RUnlock()
	fake.createOrUpdateMutex.RLock()
	defer fake.createOrUpdateMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.deallocateMutex.RLock()
	defer fake.deallocateMutex.RUnlock()
	fake.listMutex.RLock()
	defer fake.listMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeComputeVirtualMachinesClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ azure.ComputeVirtualMachinesClient = new(FakeComputeVirtualMachinesClient)
