// This file was generated by counterfeiter
package awsfakes

import (
	"sync"

	"github.com/aws/aws-sdk-go/service/ec2"
	"github.com/c0-ops/cliaas/iaas/aws"
)

type FakeInstanceDescriber struct {
	DescribeInstancesStub        func(*ec2.DescribeInstancesInput) (*ec2.DescribeInstancesOutput, error)
	describeInstancesMutex       sync.RWMutex
	describeInstancesArgsForCall []struct {
		arg1 *ec2.DescribeInstancesInput
	}
	describeInstancesReturns struct {
		result1 *ec2.DescribeInstancesOutput
		result2 error
	}
}

func (fake *FakeInstanceDescriber) DescribeInstances(arg1 *ec2.DescribeInstancesInput) (*ec2.DescribeInstancesOutput, error) {
	fake.describeInstancesMutex.Lock()
	fake.describeInstancesArgsForCall = append(fake.describeInstancesArgsForCall, struct {
		arg1 *ec2.DescribeInstancesInput
	}{arg1})
	fake.describeInstancesMutex.Unlock()
	if fake.DescribeInstancesStub != nil {
		return fake.DescribeInstancesStub(arg1)
	} else {
		return fake.describeInstancesReturns.result1, fake.describeInstancesReturns.result2
	}
}

func (fake *FakeInstanceDescriber) DescribeInstancesCallCount() int {
	fake.describeInstancesMutex.RLock()
	defer fake.describeInstancesMutex.RUnlock()
	return len(fake.describeInstancesArgsForCall)
}

func (fake *FakeInstanceDescriber) DescribeInstancesArgsForCall(i int) *ec2.DescribeInstancesInput {
	fake.describeInstancesMutex.RLock()
	defer fake.describeInstancesMutex.RUnlock()
	return fake.describeInstancesArgsForCall[i].arg1
}

func (fake *FakeInstanceDescriber) DescribeInstancesReturns(result1 *ec2.DescribeInstancesOutput, result2 error) {
	fake.DescribeInstancesStub = nil
	fake.describeInstancesReturns = struct {
		result1 *ec2.DescribeInstancesOutput
		result2 error
	}{result1, result2}
}

var _ aws.InstanceDescriber = new(FakeInstanceDescriber)
