// This file was generated by counterfeiter
package gcpfakes

import (
	"sync"

	"github.com/c0-ops/cliaas/iaas/gcp"
	compute "google.golang.org/api/compute/v1"
)

type FakeClientAPI struct {
	CreateVMStub        func(instanceName string, sourceImageTarballUrl string) error
	createVMMutex       sync.RWMutex
	createVMArgsForCall []struct {
		instanceName          string
		sourceImageTarballUrl string
	}
	createVMReturns struct {
		result1 error
	}
	DeleteVMStub        func(instanceName string) error
	deleteVMMutex       sync.RWMutex
	deleteVMArgsForCall []struct {
		instanceName string
	}
	deleteVMReturns struct {
		result1 error
	}
	GetVMInfoStub        func(filter gcp.Filter) (*compute.Instance, error)
	getVMInfoMutex       sync.RWMutex
	getVMInfoArgsForCall []struct {
		filter gcp.Filter
	}
	getVMInfoReturns struct {
		result1 *compute.Instance
		result2 error
	}
	StopVMStub        func(instanceName string) error
	stopVMMutex       sync.RWMutex
	stopVMArgsForCall []struct {
		instanceName string
	}
	stopVMReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClientAPI) CreateVM(instanceName string, sourceImageTarballUrl string) error {
	fake.createVMMutex.Lock()
	fake.createVMArgsForCall = append(fake.createVMArgsForCall, struct {
		instanceName          string
		sourceImageTarballUrl string
	}{instanceName, sourceImageTarballUrl})
	fake.recordInvocation("CreateVM", []interface{}{instanceName, sourceImageTarballUrl})
	fake.createVMMutex.Unlock()
	if fake.CreateVMStub != nil {
		return fake.CreateVMStub(instanceName, sourceImageTarballUrl)
	}
	return fake.createVMReturns.result1
}

func (fake *FakeClientAPI) CreateVMCallCount() int {
	fake.createVMMutex.RLock()
	defer fake.createVMMutex.RUnlock()
	return len(fake.createVMArgsForCall)
}

func (fake *FakeClientAPI) CreateVMArgsForCall(i int) (string, string) {
	fake.createVMMutex.RLock()
	defer fake.createVMMutex.RUnlock()
	return fake.createVMArgsForCall[i].instanceName, fake.createVMArgsForCall[i].sourceImageTarballUrl
}

func (fake *FakeClientAPI) CreateVMReturns(result1 error) {
	fake.CreateVMStub = nil
	fake.createVMReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientAPI) DeleteVM(instanceName string) error {
	fake.deleteVMMutex.Lock()
	fake.deleteVMArgsForCall = append(fake.deleteVMArgsForCall, struct {
		instanceName string
	}{instanceName})
	fake.recordInvocation("DeleteVM", []interface{}{instanceName})
	fake.deleteVMMutex.Unlock()
	if fake.DeleteVMStub != nil {
		return fake.DeleteVMStub(instanceName)
	}
	return fake.deleteVMReturns.result1
}

func (fake *FakeClientAPI) DeleteVMCallCount() int {
	fake.deleteVMMutex.RLock()
	defer fake.deleteVMMutex.RUnlock()
	return len(fake.deleteVMArgsForCall)
}

func (fake *FakeClientAPI) DeleteVMArgsForCall(i int) string {
	fake.deleteVMMutex.RLock()
	defer fake.deleteVMMutex.RUnlock()
	return fake.deleteVMArgsForCall[i].instanceName
}

func (fake *FakeClientAPI) DeleteVMReturns(result1 error) {
	fake.DeleteVMStub = nil
	fake.deleteVMReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientAPI) GetVMInfo(filter gcp.Filter) (*compute.Instance, error) {
	fake.getVMInfoMutex.Lock()
	fake.getVMInfoArgsForCall = append(fake.getVMInfoArgsForCall, struct {
		filter gcp.Filter
	}{filter})
	fake.recordInvocation("GetVMInfo", []interface{}{filter})
	fake.getVMInfoMutex.Unlock()
	if fake.GetVMInfoStub != nil {
		return fake.GetVMInfoStub(filter)
	}
	return fake.getVMInfoReturns.result1, fake.getVMInfoReturns.result2
}

func (fake *FakeClientAPI) GetVMInfoCallCount() int {
	fake.getVMInfoMutex.RLock()
	defer fake.getVMInfoMutex.RUnlock()
	return len(fake.getVMInfoArgsForCall)
}

func (fake *FakeClientAPI) GetVMInfoArgsForCall(i int) gcp.Filter {
	fake.getVMInfoMutex.RLock()
	defer fake.getVMInfoMutex.RUnlock()
	return fake.getVMInfoArgsForCall[i].filter
}

func (fake *FakeClientAPI) GetVMInfoReturns(result1 *compute.Instance, result2 error) {
	fake.GetVMInfoStub = nil
	fake.getVMInfoReturns = struct {
		result1 *compute.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeClientAPI) StopVM(instanceName string) error {
	fake.stopVMMutex.Lock()
	fake.stopVMArgsForCall = append(fake.stopVMArgsForCall, struct {
		instanceName string
	}{instanceName})
	fake.recordInvocation("StopVM", []interface{}{instanceName})
	fake.stopVMMutex.Unlock()
	if fake.StopVMStub != nil {
		return fake.StopVMStub(instanceName)
	}
	return fake.stopVMReturns.result1
}

func (fake *FakeClientAPI) StopVMCallCount() int {
	fake.stopVMMutex.RLock()
	defer fake.stopVMMutex.RUnlock()
	return len(fake.stopVMArgsForCall)
}

func (fake *FakeClientAPI) StopVMArgsForCall(i int) string {
	fake.stopVMMutex.RLock()
	defer fake.stopVMMutex.RUnlock()
	return fake.stopVMArgsForCall[i].instanceName
}

func (fake *FakeClientAPI) StopVMReturns(result1 error) {
	fake.StopVMStub = nil
	fake.stopVMReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClientAPI) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createVMMutex.RLock()
	defer fake.createVMMutex.RUnlock()
	fake.deleteVMMutex.RLock()
	defer fake.deleteVMMutex.RUnlock()
	fake.getVMInfoMutex.RLock()
	defer fake.getVMInfoMutex.RUnlock()
	fake.stopVMMutex.RLock()
	defer fake.stopVMMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeClientAPI) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gcp.ClientAPI = new(FakeClientAPI)
